repos:
# Checks the uniformity of some files
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: requirements-txt-fixer
# Checks the code format
-   repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
    -   id: black
        name: black (python)
        language_version: python3.11
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"]
